name: TEST Deployment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  init:
    name: infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform -chdir=terraform init

    - name: Format Terraform
      run: terraform fmt terraform

    - name: Plan Terraform
      run: terraform -chdir=terraform plan -out=planfile
   
    - name: Apply Terraform
      run: terraform -chdir=terraform apply --auto-approve planfile